CREATE TABLE USERS(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ENABLED BOOLEAN NOT NULL
);
CREATE TABLE ROLE(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE RATE (
    NUMCODE INT NOT NULL,
    CHARCODE VARCHAR(3) NOT NULL,
    NOMINAL INT NOT NULL,
    VALUE REAL NOT NULL
);